# Pre-commit configuration for GCP Automation API
repos:
  # Go formatting and linting
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt
        language: system
        args: [-w]
        files: \.go$

      - id: go-imports
        name: go imports
        entry: goimports
        language: system
        args: [-w]
        files: \.go$

      - id: go-vet
        name: go vet
        entry: go vet
        language: system
        args: [./...]
        files: \.go$
        pass_filenames: false

      - id: go-test
        name: go test
        entry: go test
        language: system
        args: [-v, ./tests/integration, ./tests]
        files: \.go$
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
        args: [--fix]
        files: \.go$
        pass_filenames: false

      - id: swag-init
        name: swag init (generate swagger docs)
        entry: swag
        language: system
        args:
          [
            init,
            -g,
            cmd/server/main.go,
            -o,
            docs,
            --parseDependency,
            --parseInternal,
          ]
        files: \.(go)$|handlers\.go$|models\.go$|main\.go$
        pass_filenames: false

  # Security scanning
  - repo: local
    hooks:
      - id: gosec
        name: gosec security scan
        entry: gosec
        language: system
        args: [-quiet, ./...]
        files: \.go$
        pass_filenames: false

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^docs/(swagger\.(json|yaml)|docs\.go)$
      - id: end-of-file-fixer
        exclude: ^docs/(swagger\.(json|yaml)|docs\.go)$
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-case-conflict

  # GitHub Actions linting
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        # Note: Currently reports several shellcheck and action input issues
        # Run manually with: pre-commit run actionlint --all-files
        stages: [manual]

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]
        # Note: Currently reports warnings in activate-dev.sh and install.sh
        # Run manually with: pre-commit run shellcheck --all-files
        stages: [manual]

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3009]

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: [--fix, --disable, MD013]

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml]
        exclude: ^docs/swagger\.yaml$
