name: Dependency Update

on:
  schedule:
    # Run daily at 6:00 AM UTC
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-dependencies:
    name: Update Go Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.7"

      - name: Update Go dependencies
        run: |
          go get -u ./...
          go mod tidy

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests after update
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: go test ./...

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update Go dependencies"
          title: "chore: update Go dependencies"
          body: |
            This PR updates Go dependencies to their latest versions.

            Changes:
            - Updated Go modules to latest versions
            - Ran `go mod tidy` to clean up dependencies

            Automated by GitHub Actions.
          branch: deps/update-go-dependencies
          delete-branch: true
          base: develop

  update-pre-commit:
    name: Update Pre-commit Hooks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Update pre-commit hooks
        run: |
          pre-commit autoupdate

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update pre-commit hooks"
          title: "chore: update pre-commit hooks"
          body: |
            This PR updates pre-commit hooks to their latest versions.

            Changes made by `pre-commit autoupdate`.

            Automated by GitHub Actions.
          branch: deps/update-pre-commit-hooks
          delete-branch: true
          base: develop
